<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.bteuk</groupId>
    <artifactId>Network</artifactId>
    <version>1.8.0</version>
    <packaging>pom</packaging>

    <name>Network</name>
    <modules>
        <module>Network-API</module>
        <module>Plugin</module>
        <module>Regions</module>
        <module>Core</module>
        <module>PaperCore</module>
    </modules>

    <properties>
        <java-version>21</java-version>
        <maven.compiler.release>${java-version}</maven.compiler.release>

        <paper.api.version>1.21.8-R0.1-SNAPSHOT</paper.api.version>

        <bteuk.proxy.version>c75ba196a4</bteuk.proxy.version>
        <bteuk.lib.version>5958727df9</bteuk.lib.version>

        <lombok.version>1.18.34</lombok.version>
    </properties>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <repository>
            <id>DaPorkchop_</id>
            <url>https://maven.daporkchop.net/</url>
        </repository>
        <repository>
            <id>OpenCollab Snapshots</id>
            <url>https://repo.opencollab.dev/snapshot/</url>
        </repository>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
            <layout>default</layout>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>papercore</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>regions</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.BTEUK.BTEUKLib</groupId>
                <artifactId>Minecraft</artifactId>
                <version>${bteuk.lib.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.BTEUK.Proxy</groupId>
                <artifactId>database</artifactId>
                <version>${bteuk.proxy.version}</version>
            </dependency>

            <dependency>
                <groupId>io.papermc.paper</groupId>
                <artifactId>paper-api</artifactId>
                <version>${paper.api.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
