<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.bteuk</groupId>
    <artifactId>Network</artifactId>
    <version>1.11.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Network</name>
    <modules>
        <module>Network-API</module>
        <module>Plugin</module>
        <module>Regions</module>
        <module>Core</module>
        <module>PaperCore</module>
    </modules>

    <properties>
        <java-version>21</java-version>
        <maven.compiler.release>${java-version}</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <paper.api.version>1.21.10-R0.1-SNAPSHOT</paper.api.version>

        <btuk.proxy.version>d80e385b58</btuk.proxy.version>
        <btuk.lib.version>main-36b0421e66-1</btuk.lib.version>
        <btuk.networklib.version>48f9c36fa5</btuk.networklib.version>

        <kyori.version>4.26.1</kyori.version>

        <lombok.version>1.18.34</lombok.version>

        <caffeine.version>3.2.3</caffeine.version>
    </properties>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>smyler-releases</id>
            <name>Smyler's maven repository</name>
            <url>https://maven.smyler.net/releases</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>sk89q-repo</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>central-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>papercore</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>net.bteuk.network</groupId>
                <artifactId>regions</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.BuildtheUK.BTUKLib</groupId>
                <artifactId>Minecraft</artifactId>
                <version>${btuk.lib.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.BuildtheUK</groupId>
                <artifactId>NetworkLib</artifactId>
                <version>${btuk.networklib.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.BuildtheUK.Proxy</groupId>
                <artifactId>app</artifactId>
                <version>${btuk.proxy.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.BuildtheUK.Proxy</groupId>
                <artifactId>core</artifactId>
                <version>${btuk.proxy.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.BuildtheUK.Proxy</groupId>
                <artifactId>database</artifactId>
                <version>${btuk.proxy.version}</version>
            </dependency>

            <dependency>
                <groupId>io.papermc.paper</groupId>
                <artifactId>paper-api</artifactId>
                <version>${paper.api.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>net.kyori</groupId>
                <artifactId>adventure-api</artifactId>
                <version>${kyori.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>com.github.ben-manes.caffeine</groupId>
                <artifactId>caffeine</artifactId>
                <version>${caffeine.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.6.3</version>
                    <configuration>
                        <failOnError>false</failOnError>
                        <doclint>none</doclint>
                        <encoding>UTF-8</encoding>
                    </configuration>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.1</version>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
